[package]
name = "wanaku-praxis-apis"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
name = "wanaku_praxis_apis"

[lints]
workspace = true

[dependencies]
async-trait = { workspace = true }
dashmap = { workspace = true }
utoipa = "5.5"
http = { workspace = true }
prost = { workspace = true }
rand = { workspace = true }
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "json"] }
rmcp = { version = "3.1.0", default-features = false, features = ["client", "transport-streamable-http-client-reqwest", "reqwest"] }
serde = { workspace = true }
praxis-filter = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true }
tracing = { workspace = true }

[build-dependencies]
tonic-build = "0.13"
